BEGIN;

DROP TABLE if EXISTS users;

CREATE TABLE users(
  id SERIAL PRIMARY key NOT NULL,
  username VARCHAR(100) NOT NULL UNIQUE,
  password TEXT NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  phone VARCHAR(50) NOT NULL UNIQUE
)

COMMIT
END;